# Modeling

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# โหลดข้อมูลที่ clean แล้ว
df = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/Heart-Failure-Prediction/heart_failure_clinical_records.csv')
df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    int64
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    int64
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    int64
 10  smoking                   299 non-null    int64
 11  time                      299 non-null    int64
 12  DEATH_EVENT               299 non-null    int64
dtypes: float64(3), int64(10)
memory usage: 30.5 KB

In [5]:
df.describe()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,299.000000,299.00000,299.000000,299.00000
mean,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,136.625418,0.648829,0.32107,130.260870,0.32107
std,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,4.412477,0.478136,0.46767,77.614208,0.46767
min,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,113.000000,0.000000,0.00000,4.000000,0.00000
25%,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,134.000000,0.000000,0.00000,73.000000,0.00000
50%,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,137.000000,1.000000,0.00000,115.000000,0.00000
75%,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,140.000000,1.000000,1.00000,203.000000,1.00000
max,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,148.000000,1.000000,1.00000,285.000000,1.00000

In [6]:
# ตรวจสอบ na ในข้อมูล
df.isna().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [7]:
# เปลี่ยน data type ของ column
df['anaemia'] = df['anaemia'].astype(str)
df['diabetes'] = df['diabetes'].astype(str)
df['high_blood_pressure'] = df['high_blood_pressure'].astype(str)
df['sex'] = df['sex'].astype(str)
df['smoking'] = df['smoking'].astype(str)
df['DEATH_EVENT'] = df['DEATH_EVENT'].astype(str)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    object
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    object
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    object
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    object
 10  smoking                   299 non-null    object
 11  time                      299 non-null    int64
 12  DEATH_EVENT               299 non-null    object
dtypes: float64(3), int64(4), object(6)
memory usage: 30.5+ KB

In [9]:
df_cat  = pd.get_dummies(df.select_dtypes('object') , drop_first=True)
df_cat

,anaemia_1,diabetes_1,high_blood_pressure_1,sex_1,smoking_1,DEATH_EVENT_1
0,0,0,1,1,0,1
1,0,0,0,1,0,1
2,0,0,0,1,1,1
3,1,0,0,1,0,1
4,1,1,0,0,0,1
...,...,...,...,...,...,...
294,0,1,1,1,1,0
295,0,0,0,0,0,0
296,0,1,0,0,0,0
297,0,0,0,1,1,0
298,0,0,0,1,1,0

In [10]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   anaemia_1              299 non-null    uint8
 1   diabetes_1             299 non-null    uint8
 2   high_blood_pressure_1  299 non-null    uint8
 3   sex_1                  299 non-null    uint8
 4   smoking_1              299 non-null    uint8
 5   DEATH_EVENT_1          299 non-null    uint8
dtypes: uint8(6)
memory usage: 1.9 KB

In [11]:
df_num = df.select_dtypes('number')
df_num

,age,creatinine_phosphokinase,ejection_fraction,platelets,serum_creatinine,serum_sodium,time
0,75.0,582,20,265000.00,1.9,130,4
1,55.0,7861,38,263358.03,1.1,136,6
2,65.0,146,20,162000.00,1.3,129,7
3,50.0,111,20,210000.00,1.9,137,7
4,65.0,160,20,327000.00,2.7,116,8
...,...,...,...,...,...,...,...
294,62.0,61,38,155000.00,1.1,143,270
295,55.0,1820,38,270000.00,1.2,139,271
296,45.0,2060,60,742000.00,0.8,138,278
297,45.0,2413,38,140000.00,1.4,140,280
298,50.0,196,45,395000.00,1.6,136,285

In [12]:
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   creatinine_phosphokinase  299 non-null    int64
 2   ejection_fraction         299 non-null    int64
 3   platelets                 299 non-null    float64
 4   serum_creatinine          299 non-null    float64
 5   serum_sodium              299 non-null    int64
 6   time                      299 non-null    int64
dtypes: float64(3), int64(4)
memory usage: 16.5 KB

In [13]:
# from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [14]:
df_num_scaler = MinMaxScaler().fit_transform(df_num)
df_num_scaler

array([[0.63636364, 0.07131921, 0.09090909, ..., 0.15730337, 0.48571429,
        0.        ],
       [0.27272727, 1.        , 0.36363636, ..., 0.06741573, 0.65714286,
        0.00711744],
       [0.45454545, 0.01569278, 0.09090909, ..., 0.08988764, 0.45714286,
        0.01067616],
       ...,
       [0.09090909, 0.25988773, 0.6969697 , ..., 0.03370787, 0.71428571,
        0.97508897],
       [0.09090909, 0.30492473, 0.36363636, ..., 0.1011236 , 0.77142857,
        0.98220641],
       [0.18181818, 0.02207196, 0.46969697, ..., 0.12359551, 0.65714286,
        1.        ]])

In [15]:
df_num_scaler_final = pd.DataFrame(df_num_scaler, columns=df_num.columns, index=df_num.index)
df_num_scaler_final

,age,creatinine_phosphokinase,ejection_fraction,platelets,serum_creatinine,serum_sodium,time
0,0.636364,0.071319,0.090909,0.290823,0.157303,0.485714,0.000000
1,0.272727,1.000000,0.363636,0.288833,0.067416,0.657143,0.007117
2,0.454545,0.015693,0.090909,0.165960,0.089888,0.457143,0.010676
3,0.181818,0.011227,0.090909,0.224148,0.157303,0.685714,0.010676
4,0.454545,0.017479,0.090909,0.365984,0.247191,0.085714,0.014235
...,...,...,...,...,...,...,...
294,0.400000,0.004848,0.363636,0.157474,0.067416,0.857143,0.946619
295,0.272727,0.229268,0.363636,0.296884,0.078652,0.742857,0.950178
296,0.090909,0.259888,0.696970,0.869075,0.033708,0.714286,0.975089
297,0.090909,0.304925,0.363636,0.139290,0.101124,0.771429,0.982206
298,0.181818,0.022072,0.469697,0.448418,0.123596,0.657143,1.000000

In [16]:
df_final = pd.concat([df_num_scaler_final, df_cat],axis=1) # axis=1 จะเป็นการต่อในแนวนอน
df_final

,age,creatinine_phosphokinase,ejection_fraction,platelets,serum_creatinine,serum_sodium,time,anaemia_1,diabetes_1,high_blood_pressure_1,sex_1,smoking_1,DEATH_EVENT_1
0,0.636364,0.071319,0.090909,0.290823,0.157303,0.485714,0.000000,0,0,1,1,0,1
1,0.272727,1.000000,0.363636,0.288833,0.067416,0.657143,0.007117,0,0,0,1,0,1
2,0.454545,0.015693,0.090909,0.165960,0.089888,0.457143,0.010676,0,0,0,1,1,1
3,0.181818,0.011227,0.090909,0.224148,0.157303,0.685714,0.010676,1,0,0,1,0,1
4,0.454545,0.017479,0.090909,0.365984,0.247191,0.085714,0.014235,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,0.400000,0.004848,0.363636,0.157474,0.067416,0.857143,0.946619,0,1,1,1,1,0
295,0.272727,0.229268,0.363636,0.296884,0.078652,0.742857,0.950178,0,0,0,0,0,0
296,0.090909,0.259888,0.696970,0.869075,0.033708,0.714286,0.975089,0,1,0,0,0,0
297,0.090909,0.304925,0.363636,0.139290,0.101124,0.771429,0.982206,0,0,0,1,1,0
298,0.181818,0.022072,0.469697,0.448418,0.123596,0.657143,1.000000,0,0,0,1,1,0

In [18]:
df_final.to_csv('heart_failure_clinical_records-scaled.csv', index=False)



---